export * from './createHead'
export * from './legacy'
export * from './components'
export type { Unhead, HeadEntryOptions, MaybeComputedRef, UseHeadInput, MergeHead, ReactiveHead } from '@unhead/vue'
export { useHead, useServerHead, VueHeadMixin } from '@unhead/vue'
